### ISSUE TITLE
Go public and announce the thing

### ISSUE THREAD

**Issue by matthid** [matthid/csharptofsharp#14]
Questions to solve:
- [ ] Should it stay on my GitHub account or should we add a `cs2fs` organization? Add it somewhere else (fsprojects for example)?

Issues to solve (imho to accept contributions):
- [ ] https://github.com/matthid/csharptofsharp/issues/13 in a perfect world we have a staging environment like https://staging.fake.build.
- [ ] https://github.com/matthid/csharptofsharp/issues/11
- [ ] (would be nice...) https://github.com/matthid/csharptofsharp/issues/5
- [ ] (would be nice because people can contribute hints) https://github.com/matthid/csharptofsharp/issues/12
